name: Copy README to gh-pages branch
on:
  push:
    branches: [master]
    paths: ["README.md"]

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: "gh-pages"

      - name: copy README to gh-pages branch
        run: |
          git fetch --depth=1 origin master
          git checkout origin/master README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit README.md -m 'Copy readme file from master branch'
          git push origin gh-pages
